Updates
rticommunity/rticonnextdds-usecases-umaa pull request #5
Opened 2024-05-31 00:02 UTC by rtidgreenberg

- Cleaned up QOS assignment
- Created GPS component to add reference example re: indexing into sequence of sub types

2024-06-10 11:44 UTC, angelrti requested changes

2024-06-10 11:44 UTC, angelrti commented on examples/python/gps.py
> +    params.url_profile = [file]
As this is an example, probably you may want to add a comment here explaining the differences between the url_profile and the QosProvider (both of them use the same `file`)

2024-06-11 22:05 UTC, rtidgreenberg commented
updated documentation/comments

2024-06-13 10:36 UTC, angelrti approved these changes

2024-06-13 15:33 UTC, merged